version: '3'
name: rate-limiter-project
services:
  redis-db:
    image: redis:7.2.4-alpine
    restart: always
    container_name: redis-db
    ports:
      - 6379:6379
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis-db
    container_name: rate-limiter-app
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis-db:6379
